/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  Shuffle_encryptPairing5Card,
  Shuffle_encryptPairing5CardInterface,
} from "../../../../../@poseidon-zkp/poseidon-zk-circuits/contracts/shuffle_encrypt_verifier_5card.sol/Shuffle_encryptPairing5Card";

const _abi = [
  {
    inputs: [],
    name: "InvalidProof",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220490d982e6665987a8f245e1cb0c91326b0e7decdd80a38bd2659d59507d655ea64736f6c63430008040033";

type Shuffle_encryptPairing5CardConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Shuffle_encryptPairing5CardConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Shuffle_encryptPairing5Card__factory extends ContractFactory {
  constructor(...args: Shuffle_encryptPairing5CardConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Shuffle_encryptPairing5Card> {
    return super.deploy(
      overrides || {}
    ) as Promise<Shuffle_encryptPairing5Card>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Shuffle_encryptPairing5Card {
    return super.attach(address) as Shuffle_encryptPairing5Card;
  }
  override connect(signer: Signer): Shuffle_encryptPairing5Card__factory {
    return super.connect(signer) as Shuffle_encryptPairing5Card__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Shuffle_encryptPairing5CardInterface {
    return new utils.Interface(_abi) as Shuffle_encryptPairing5CardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Shuffle_encryptPairing5Card {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as Shuffle_encryptPairing5Card;
  }
}
