/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  Decrypt,
  DecryptInterface,
} from "../../../../contracts/decrypt/decrypt.sol/Decrypt";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220e6ee307d780f4cdc96b6277e2653b1a7050297c56034f55a63b7e84049cc818f64736f6c63430008040033";

type DecryptConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DecryptConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Decrypt__factory extends ContractFactory {
  constructor(...args: DecryptConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Decrypt> {
    return super.deploy(overrides || {}) as Promise<Decrypt>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Decrypt {
    return super.attach(address) as Decrypt;
  }
  override connect(signer: Signer): Decrypt__factory {
    return super.connect(signer) as Decrypt__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DecryptInterface {
    return new utils.Interface(_abi) as DecryptInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Decrypt {
    return new Contract(address, _abi, signerOrProvider) as Decrypt;
  }
}
