/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISignal,
  ISignalInterface,
} from "../../../contracts/signal/ISignal";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "rc",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "message",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "nullifierHash",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "externalNullifier",
        type: "uint256",
      },
      {
        internalType: "uint256[8]",
        name: "proof",
        type: "uint256[8]",
      },
    ],
    name: "signal",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISignal__factory {
  static readonly abi = _abi;
  static createInterface(): ISignalInterface {
    return new utils.Interface(_abi) as ISignalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISignal {
    return new Contract(address, _abi, signerOrProvider) as ISignal;
  }
}
