/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftSol from "./NFT.sol";
export type { nftSol };
import type * as voteSol from "./vote.sol";
export type { voteSol };
