/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as signalSol from "./signal.sol";
export type { signalSol };
export type { ISignal } from "./ISignal";
