/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  SignalPairing,
  SignalPairingInterface,
} from "../../../../../@p0x-labs/poseidon-zk-circuits/contracts/signal_verifier.sol/SignalPairing";

const _abi = [
  {
    inputs: [],
    name: "InvalidProof",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220da7887ccbefcdd1d3ee5dd0db7f701cee9c9412cbd2fb9f56487fd11fa484c7864736f6c63430008040033";

type SignalPairingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SignalPairingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SignalPairing__factory extends ContractFactory {
  constructor(...args: SignalPairingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<SignalPairing> {
    return super.deploy(overrides || {}) as Promise<SignalPairing>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SignalPairing {
    return super.attach(address) as SignalPairing;
  }
  override connect(signer: Signer): SignalPairing__factory {
    return super.connect(signer) as SignalPairing__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SignalPairingInterface {
    return new utils.Interface(_abi) as SignalPairingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SignalPairing {
    return new Contract(address, _abi, signerOrProvider) as SignalPairing;
  }
}
