/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  Shuffle_encryptPairing,
  Shuffle_encryptPairingInterface,
} from "../../../../../@p0x-labs/poseidon-zk-circuits/contracts/shuffle_encrypt_verifier.sol/Shuffle_encryptPairing";

const _abi = [
  {
    inputs: [],
    name: "InvalidProof",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212203e575f825ac975c047b2b1f1ade1e7d14bb8b53ebe62c9d49a260ded9af1253864736f6c63430008040033";

type Shuffle_encryptPairingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Shuffle_encryptPairingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Shuffle_encryptPairing__factory extends ContractFactory {
  constructor(...args: Shuffle_encryptPairingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Shuffle_encryptPairing> {
    return super.deploy(overrides || {}) as Promise<Shuffle_encryptPairing>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Shuffle_encryptPairing {
    return super.attach(address) as Shuffle_encryptPairing;
  }
  override connect(signer: Signer): Shuffle_encryptPairing__factory {
    return super.connect(signer) as Shuffle_encryptPairing__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Shuffle_encryptPairingInterface {
    return new utils.Interface(_abi) as Shuffle_encryptPairingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Shuffle_encryptPairing {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as Shuffle_encryptPairing;
  }
}
