/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as groupSol from "./group.sol";
export type { groupSol };
export type { IGroup } from "./IGroup";
