/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace Shuffle_encrypt_v2Pairing {
  export type G1PointStruct = {
    X: PromiseOrValue<BigNumberish>;
    Y: PromiseOrValue<BigNumberish>;
  };

  export type G1PointStructOutput = [BigNumber, BigNumber] & {
    X: BigNumber;
    Y: BigNumber;
  };
}

export interface ShuffleEncryptV2VerifierKeyInterface extends utils.Interface {
  functions: {
    "vkeyPart2()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "vkeyPart2"): FunctionFragment;

  encodeFunctionData(functionFragment: "vkeyPart2", values?: undefined): string;

  decodeFunctionResult(functionFragment: "vkeyPart2", data: BytesLike): Result;

  events: {};
}

export interface ShuffleEncryptV2VerifierKey extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShuffleEncryptV2VerifierKeyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    vkeyPart2(
      overrides?: CallOverrides
    ): Promise<
      [Shuffle_encrypt_v2Pairing.G1PointStructOutput[]] & {
        IC: Shuffle_encrypt_v2Pairing.G1PointStructOutput[];
      }
    >;
  };

  vkeyPart2(
    overrides?: CallOverrides
  ): Promise<Shuffle_encrypt_v2Pairing.G1PointStructOutput[]>;

  callStatic: {
    vkeyPart2(
      overrides?: CallOverrides
    ): Promise<Shuffle_encrypt_v2Pairing.G1PointStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    vkeyPart2(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    vkeyPart2(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
