/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  ExamplePairing,
  ExamplePairingInterface,
} from "../../../../../@p0x-labs/poseidon-zk-circuits/contracts/example_verifier.sol/ExamplePairing";

const _abi = [
  {
    inputs: [],
    name: "InvalidProof",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122096063b7cca37845140555f1b3fef231f4dbd118ebe75a1f6adb784681de1439e64736f6c63430008040033";

type ExamplePairingConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExamplePairingConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExamplePairing__factory extends ContractFactory {
  constructor(...args: ExamplePairingConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ExamplePairing> {
    return super.deploy(overrides || {}) as Promise<ExamplePairing>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ExamplePairing {
    return super.attach(address) as ExamplePairing;
  }
  override connect(signer: Signer): ExamplePairing__factory {
    return super.connect(signer) as ExamplePairing__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExamplePairingInterface {
    return new utils.Interface(_abi) as ExamplePairingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExamplePairing {
    return new Contract(address, _abi, signerOrProvider) as ExamplePairing;
  }
}
